#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"
title: A.I. Nagy
name: Attila István Nagy M.D.
author:
  name     : "Attila István Nagy"
  avatar   : "/assets/images/nai2.jpg"
  bio      : "Psychiatrist and AI enthusiast. Driven by a desire to understand, improve and create, my mission is to improve lives and transcend limits."
  location : "Debrecen, Hungary"
subtitle: Optimizing Consciousness since 2010.
description: My official presence on GitHub
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
custom_css:
  - assets/css/custom.css
